version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /CodeBuild/DOCKERHUB_USERNAME
    DOCKER_REGISTRY_PASSWORD: /CodeBuild/DOCKERHUB_PASSWORD


phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t html:latest .
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to Docker Hub...
      - docker push html:latest

artifacts:
  files:
    - '**/*'
