version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t krishna2947/html . || exit 1
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to Docker Hub...
      - docker push krishna2947/html || exit 1

artifacts:
  files:
    - '**/*'
